version: '3'
services:
  node:
    build:
      context: .
      args:
        PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./logs:/usr/app/logs
      - ./src:/usr/app/src
    environment:
      - PORT=${PORT}
    restart: always
    networks:
      - net
  postgres:
    build: ./database/
    ports: 
      - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - net
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${APP_SUBNET}
